services:
  vaultwarden:
    container_name: vaultwarden
    deploy:
      resources:
        limits:
          cpus: ${SERVICE_LIMIT_CPU:-0.50}
          memory: ${SERVICE_LIMIT_MEMORY:-256M}
    env_file: .env
    image: vaultwarden/server:latest-alpine
    ports:
      - ${SERVICE_PORT:-80}:80
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    user: 1000:1000
    volumes:
      - ${SERVICE_FOLDER_DATA:-./data}:/data
