services:
  beaverhabits:
    container_name: beaverhabits
    deploy:
      resources:
        limits:
          cpus: ${SERVICE_LIMIT_CPU}
          memory: ${SERVICE_LIMIT_MEMORY}
    env_file:
      - .env
    image: daya0576/beaverhabits:latest
    ports:
      - ${SERVICE_PORT}:8080
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    user: 1000:1000
    volumes:
      - ${SERVICE_FOLDER_DATA}:/app/.user/
