services:
  db:
    container_name: warracker_db
    deploy:
      resources:
        limits:
          cpus: ${SERVICE_LIMIT_CPU_DB:-0.50}
          memory: ${SERVICE_LIMIT_MEMORY_DB:-512M}
    env_file: .env
    image: 11notes/postgres:16
    read_only: true
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /postgres/run:uid=1000,gid=1000
      - /postgres/log:uid=1000,gid=1000
    volumes:
      - postgres.etc:/postgres/etc
      - postgres.var:/postgres/var
      - ${SERVICE_FOLDER_BACKUP:-./backup}:/postgres/backup

  warracker:
    container_name: warracker
    depends_on:
      db:
        condition: service_healthy
        restart: true
    deploy:
      resources:
        limits:
          cpus: ${SERVICE_LIMIT_CPU:-0.50}
          memory: ${SERVICE_LIMIT_MEMORY:-512M}
    env_file: .env
    image: ghcr.io/sassanix/warracker/main:latest
    ports:
      - ${SERVICE_PORT:-80}:80
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - ${SERVICE_FOLDER_UPLOADS:-./uploads}:/data/uploads

volumes:
  postgres.etc:
  postgres.var:
