services:
  diun:
    container_name: diun
    deploy:
      resources:
        limits:
          cpus: ${SERVICE_LIMIT_CPU:-0.50}
          memory: ${SERVICE_LIMIT_MEMORY:-256M}
    env_file: .env
    image: crazymax/diun:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    user: 1000:988
    volumes:
      - ${SERVICE_FOLDER_DATA:-./data}:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
