services:
  karakeep:
    container_name: karakeep
    deploy:
      resources:
        limits:
          cpus: ${SERVICE_LIMIT_CPU:-1.00}
          memory: ${SERVICE_LIMIT_MEMORY:-1G}
    env_file: .env
    image: ghcr.io/karakeep-app/karakeep:release
    ports:
      - ${SERVICE_PORT:-3000}:3000
    restart: unless-stopped
    user: 1000:1000
    volumes:
      - ${SERVICE_FOLDER_DATA:-./data}:/data

  chrome:
    container_name: karakeep_chrome
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
    deploy:
      resources:
        limits:
          cpus: ${SERVICE_LIMIT_CPU_CHROME:-1.00}
          memory: ${SERVICE_LIMIT_MEMORY_CHROME:-512M}
    image: gcr.io/zenika-hub/alpine-chrome:124
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

  meilisearch:
    container_name: karakeep_search
    deploy:
      resources:
        limits:
          cpus: ${SERVICE_LIMIT_CPU_SEARCH:-1.00}
          memory: ${SERVICE_LIMIT_MEMORY_SEARCH:-1G}
    env_file: .env
    image: getmeili/meilisearch:v1.13.3
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - meilisearch:/meili_data

volumes:
  meilisearch:
